// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	about: NamespaceAboutTranslation
}

type RootTranslation = {
	/**
	 * t​y​p​e​s​a​f​e​-​i​1​8​n​ ​-​ ​S​v​e​l​t​e​ ​F​a​l​l​ ​S​u​m​m​i​t​ ​{​y​e​a​r​}
	 * @param {number} year
	 */
	title: RequiredParams<'year'>
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​S​v​e​l​t​e​ ​F​a​l​l​ ​S​u​m​m​i​t​ ​{​y​e​a​r​}
	 * @param {number} year
	 */
	welcome: RequiredParams<'year'>
	/**
	 * {​0​}​ ​l​i​v​e​ ​s​p​e​c​t​a​t​o​r​{​{​s​}​}
	 * @param {string | number | boolean} 0
	 */
	spectators: RequiredParams<'0'>
	summit: {
		/**
		 * {​0​|​s​i​m​p​l​e​D​a​t​e​}
		 * @param {Date} 0
		 */
		schedule: RequiredParams<'0|simpleDate'>
	}
}

export type NamespaceAboutTranslation = {
	/**
	 * A​b​o​u​t​ ​t​y​p​e​s​a​f​e​-​i​1​8​n
	 */
	title: string
}

export type Namespaces =
	| 'about'

type DisallowNamespaces = {
	/**
	 * reserved for 'about'-namespace\
	 * you need to use the `./about/index.ts` file instead
	 */
	about?: "[typesafe-i18n] reserved for 'about'-namespace. You need to use the `./about/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * typesafe-i18n - Svelte Fall Summit {year}
	 */
	title: (arg: { year: number }) => LocalizedString
	/**
	 * Welcome to Svelte Fall Summit {year}
	 */
	welcome: (arg: { year: number }) => LocalizedString
	/**
	 * {0} live spectator{{s}}
	 */
	spectators: (arg0: string | number | boolean) => LocalizedString
	summit: {
		/**
		 * {0|simpleDate}
		 */
		schedule: (arg0: Date) => LocalizedString
	}
	about: {
		/**
		 * About typesafe-i18n
		 */
		title: () => LocalizedString
	}
}

export type Formatters = {
	simpleDate: (value: Date) => unknown
}
