// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
// @ts-check
/* eslint-disable */

/**
 * @typedef { import('./i18n-types').Locales } Locales
 * @typedef { import('./i18n-types').Namespaces } Namespaces
 * @typedef { import('./i18n-types').Translations } Translations
 */

import { initFormatters } from './formatters'

import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslationLoaders = {
	de: () => import('./de'),
	en: () => import('./en'),
	it: () => import('./it'),
}

const localeNamespaceLoaders = {
	de: {
		about: () => import('./de/about')
	},
	en: {
		about: () => import('./en/about')
	},
	it: {
		about: () => import('./it/about')
	}
}

/**
 * @param { Locales } locale
 * @param { Partial<Translations> } dictionary
 * @return { Translations }
 */
const updateDictionary = (locale, dictionary) =>
	loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }

/**
 * @param { Locales } locale
 * @return { Promise<Translations> }
 */
export const importLocaleAsync = async (locale) =>
	/** @type { Translations } */ (/** @type { unknown } */ ((await localeTranslationLoaders[locale]()).default))

/**
 * @param { Locales } locale
 * @return { Promise<void> }
 */
export const loadLocaleAsync = async (locale) => {
	updateDictionary(locale, await importLocaleAsync(locale))
	loadFormatters(locale)
}

export const loadAllLocalesAsync = () => Promise.all(locales.map(loadLocaleAsync))

/**
 * @param { Locales } locale
 * @return { void }
 */
export const loadFormatters = (locale) =>
	void (loadedFormatters[locale] = initFormatters(locale))

/**
 * @param { Locales } locale
 * @param { Namespaces } namespace
 * @return { Promise<Translations[namespace]> }
 */
export const importNamespaceAsync = async(locale, namespace) =>
	(await localeNamespaceLoaders[locale][namespace]()).default

/**
 * @param { Locales } locale
 * @param { Namespaces } namespace
 * @return { Promise<void> }
 */
export const loadNamespaceAsync = async (locale, namespace) =>
	void updateDictionary(locale, { [namespace]: await importNamespaceAsync(locale, namespace )})
