// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
// @ts-check
/* eslint-disable */

/**
 * @typedef { import('typesafe-i18n/adapters/adapter-svelte').SvelteStoreInit<Locales, Translation, TranslationFunctions> } SvelteStoreInit,
 * @typedef { import('./i18n-types').Locales } Locales,
 * @typedef { import('./i18n-types').Translation } Translation,
 * @typedef { import('./i18n-types').TranslationFunctions } TranslationFunctions,
 * @typedef { import('./i18n-types').Formatters } Formatters
 */

import { getI18nSvelteStore } from 'typesafe-i18n/adapters/adapter-svelte';

import { baseLocale, getTranslationForLocale } from './i18n-util'
import { initFormatters } from './formatters'

/** @type { SvelteStoreInit } */
const { initI18n: init, setLocale, isLoadingLocale, locale, LL } = getI18nSvelteStore()

/**
 * @param { Locales } locale
 * @return { Promise<void> }
 */
const initI18n = (locale = baseLocale) => init(locale, getTranslationForLocale, initFormatters)

export { initI18n, setLocale, isLoadingLocale, locale, LL }

export default LL
